name: my_story_app
description: "Write your own story."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  fluentui_system_icons: ^1.1.246
  dot_navigation_bar: ^1.0.2
  carousel_slider: ^4.2.1
  get_it: ^7.7.0
  http: ^1.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  meta: ^1.12.0
  skeletonizer: ^1.3.0
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  get_it_mixin: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
